spring:
  datasource:
    url: jdbc:h2:mem:test
    username: h2
    password: h2
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

server:
  port: 8090

app:
  jwt-secret: JWTSecretKey
  jwt-expiration-milliseconds: 604800000